job_name: 'example_job'

general:
    days_to_predict: [1,2,3,4,5]
    years: [2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016]
    data:
        data_dir: '../data/'
        data_sources:
            detections: 'interim/modies/fire_cube/fire_detection_cube_modis_alaska_2007-2016.pkl'
            land_cover: 'interim/land_cover/land_cover_alaska.pkl'
            weather: 'interim/gfs/weather_proc/4/weather_proc_gfs_4_alaska_2007-2016.pkl'
    model:
        model_name: 'active_ignition_grid_model'
        active:
            model_name: 'poisson_regression_grid_model'
            filter_func: 'active_filter'
            pred_func: 'active_pred'
        ignition: None
    covariates: 
        weather: ['temperature', 'humidity', 'wind', 'rain']
        land_cover: None
        water_mask: True
        region_biases: None
    memory:
        memory_interval: 10
        decay_rate: .25

experiments:
    experiment1:
        name: 'baseline'
    experiment2:
        name: 'adding_land_cover'


